name: expense_tracker
description: An expense tracker app to help you track your money.

environment:
  sdk: '>=3.0.0 <4.0.0'  # â† ADD THIS LINE

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.66.0
  intl: ^0.18.1
  csv: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true